export const actionTypes = {
    ADD_CONTENT: "ADD_CONTENT",
    GET_CONTENT: "GET_CONTENT",
    UPDATE_CONTENT: "UPDATE_CONTENT",
    DELETE_CONTENT: "DELETE_CONTENT",
    READ_BLOG: "READ_BLOG",
    SET_SORT: "SET_SORT",
    FILTER_CATEGORY: "FILTER_CATEGORY",
}